Use MD5Builder library to generate MD5 for ESP8266
The ESP8266 core library has a file named md5.h, which gets included
instead of MD5.h on case insensitive operating systems, causing the
error:

MD5 not declared

I'm still getting the error:

error: __c causes a section type conflict with __c

when authentication is used but this does get one step closer to ESP8266
compatibility. NoAuthentication.ino does compile (with or without this
commit).